# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-27 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('movie_description', models.CharField(max_length=150)),
            ],
        ),
    ]
